### PR TITLE
Get rid of go routines within server metrics

### PR DESCRIPTION
**Pull request by tboerger**
Fixes https://github.com/promhippie/hcloud_exporter/issues/70

### CODE REVIEW

**Comment by JanKoppe** [comment]
Really weird that this is happening. The reason for goroutines being used is that the server metrics endpoint are really, really slow. goroutines allowed parallel requests, making this much less critical.

**Comment by tboerger** [comment]
I know, but since I haven't been able to reproduce this error it had sadly been easier to remove the go routines with the disadvantage that the metrics scraping gets slowed down.

**Comment by tboerger** [comment]
Damn, maybe it would also help to add `ch` as a parameter to the routine. Haven't tried that. But it's not easy to test if the error doesn't happen to me.

**Comment by JanKoppe** [comment]
I can take another look at this on the weekend, and see if I can fix it. We're running a large amount of hetzner cloud servers at work, so I might have a better chance of reproducing this issue. I'm just not very experienced with Go, so it might well be a stupid beginners mistake.

It might make sense to disable this collector by default until those issues are ironed out for now?

**Comment by tboerger** [comment]
As there have been another report at #74 it would make sense to disable it by default for now until we resolve the issues.

Looks like the timeout values also got to be improved.

Feel free to create a pull request and we get the code right. Doesn't matter if you are a beginner with go :)

**Pull request merged**
