### PR TITLE
Adds a helm chart 

### PR DESCRIPTION
**Pull request by ErwinSteffens**
We are using this Helm chart to deploy the exporter to Kubernetes. I am creating this PR because maybe it can be of value to this project?

It would be great if we could create a charts repository at https://github.com/promhippie/charts, so we can maybe at multiple charts in the future and publish them at the ArtifactHUB (https://artifacthub.io/).

### CODE REVIEW

**Comment by tboerger** [comment]
Thanks for the contribution, I will come up with a charts repository soon and than I will also publish it to Artifacthub.

**Comment by tboerger** [comment]
Not exactly what you are waiting for, but at least some other start for Kubernetes deployments, I have created a PR for a Kustomize manifest at https://github.com/promhippie/hcloud_exporter/pull/52.

I will try to prepare the Helm stuff within the next days.

**Comment by tboerger** [comment]
Finally I have published the GitHub and Hetzner Cloud exporter at https://artifacthub.io/packages/search?org=promhippie, you can find the sources at https://github.com/promhippie/charts. Thank you for your efforts!

**Comment by tboerger** [comment]
Finally I have published the GitHub and Hetzner Cloud exporter at https://artifacthub.io/packages/search?org=promhippie, you can find the sources at https://github.com/promhippie/charts. Thank you for your efforts!

**Comment by ErwinSteffens** [comment]
Awesome, thank you!

**Pull request closed without merging**
